-- Удаляем таблицы, если они уже существуют
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE reports_archive';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE orders';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE users';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Создаём таблицы заново
CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100),
  created_date DATE DEFAULT SYSDATE
);

CREATE TABLE orders (
  order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER REFERENCES users(user_id),
  amount NUMBER,
  order_date DATE DEFAULT SYSDATE
);

CREATE TABLE reports_archive (
  report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_month VARCHAR2(7),
  total_users NUMBER
);
